steps:
  - name: gcr.io/cloud-builders/docker
    args: [ build, --build-arg, PROJECT_ID=$PROJECT_ID, -t, gcr.io/$PROJECT_ID/optimizetools-ui, . ]
  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instance-groups, managed, rolling-action, replace, instance-group-optimize-tools-ui, --zone=us-central1-b ]
  
images:
  - gcr.io/$PROJECT_ID/optimizetools-ui
